#!/usr/bin/env bash

# chmod +x vscode/setup
# vscode/setup 

ln -sf $HOME/Developer/dotfiles/vscode/settings.json $HOME/Library/Application\ Support/Code/User

# 1 Save => code --list-extensions > ~/dotfiles/apps/vscode/extensions
# Install:
cat $HOME/Developer/dotfiles/vscode/extensions | xargs -L 1 code --install-extension

# vim: set ft=sh
