#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = 'coc'
    statusline_unicode_symbols = false

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'git'

[[layers]]
  name = 'github'


[[layers]]
  name = 'lang#WebAssembly'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#elixir'

[[layers]]
  name = 'lang#erlang'

# Depends on:
# - Depending on how you manage your dependencies:
#   - Simple `gem install solargraph` 
#   - nix-env -iA nixpkgs.solargraph + solargraph bundle
# - :CocInstall coc-solargraph
[[layers]]
  name = 'lang#ruby'

[[layers]]
  name = 'lang#javascript'

[[layers]]
  name = 'lang#typescript'
  typescript_server_path = 'usr/local/bin/tsserver'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'tmux'


[[custom_plugins]]
  name = 'chriskempson/base16-vim'
  merged = false

