[options]
  bootstrap_after = "myspacevim#after"
  colorscheme = "NeoSolarized"
  colorscheme_bg = "light"
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_inactive_separator = "nil"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  autocomplete_method = 'deoplete'
  statusline_unicode_symbols = false
  enable_neomake = false
  enable_ale = true

  disabled_plugins = ["slashmili/alchemist.vim"]

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'git'

[[layers]]
  name = 'github'

[[layers]]
  name = 'lang#WebAssembly'

[[layers]]
  name = 'lang#swift'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#elixir'

[[layers]]
  name = 'lang#erlang'

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = "lang#crystal"


# Depends on:
# - Depending on how you manage your dependencies:
#   - Simple `gem install solargraph` or 
#   - nix-env -iA nixpkgs.solargraph + solargraph bundle
# - :CocInstall coc-solargraph
[[layers]]
  name = 'lang#ruby'

[[layers]]
  name = 'lang#javascript'

[[layers]]
  name = 'lang#typescript'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'tmux'

[[layers]]
  name = "lang#ocaml"

[[layers]]
  name = "core#tabline"
  enable = false

[[layers]]
  name = "lang#nix"

[[layers]]
  name = "lang#coffeescript"

[[custom_plugins]]
  name = 'chriskempson/base16-vim'
  merged = false

[[custom_plugins]]
  name = "junegunn/goyo.vim"
  merged = false

[[custom_plugins]]
  name = "jreybert/vimagit"
  merged = false

[[custom_plugins]]
  name = "reasonml-editor/vim-reason-plus"
  merged = false
  
[[custom_plugins]]
  name = "tpope/vim-rails"
  merged = false

[[custom_plugins]]
  name =  "vimwiki/vimwiki"
  merged = false

[[custom_plugins]]
  name = "pechorin/any-jump.vim"
  merged = false

[[custom_plugins]]
  name = "ollykel/v-vim"
  merged = false

[[custom_plugins]]
  name = "icymind/NeoSolarized"
  merged = false

[[custom_plugins]]
  name = "merlinrebrovic/focus.vim"
  merged = false

[[custom_plugins]]
  name = "autozimu/LanguageClient-neovim"
  merged = false

[[custom_plugins]]
  name = "neovimhaskell/haskell-vim"
  merged = false
